package cn.sliew.milky.common.util;

import java.util.function.Function;

import static cn.sliew.milky.common.check.Ensures.checkNotNull;
import static java.util.Arrays.stream;
import static java.util.stream.Collectors.joining;

public final class ClassUtil {

    private ClassUtil() {
        throw new IllegalStateException("can't do this!");
    }

    /**
     * Get the fully qualified name of the supplied class.
     *
     * <p>This is a null-safe variant of {@link Class#getName()}.
     *
     * @param clazz the class whose name should be retrieved, potentially {@code null}
     * @return the fully qualified class name or {@code "null"} if the supplied
     * class reference is {@code null}
     * @see #nullSafeToString(Class...)
     * @see StringUtils#nullSafeToString(Object)
     */
    public static String nullSafeToString(Class<?> clazz) {
        return clazz == null ? "null" : clazz.getName();
    }

    /**
     * Generate a comma-separated list of fully qualified class names for the
     * supplied classes.
     *
     * @param classes the classes whose names should be included in the generated string
     * @return a comma-separated list of fully qualified class names, or an empty
     * string if the supplied class array is {@code null} or empty
     * @see #nullSafeToString(Function, Class...)
     * @see StringUtils#nullSafeToString(Object)
     */
    public static String nullSafeToString(Class<?>... classes) {
        return nullSafeToString(Class::getName, classes);
    }

    /**
     * Generate a comma-separated list of mapped values for the supplied classes.
     *
     * <p>The values are generated by the supplied {@code mapper}
     * (e.g., {@code Class::getName}, {@code Class::getSimpleName}, etc.), unless
     * a class reference is {@code null} in which case it will be mapped to {@code "null"}.
     *
     * @param mapper  the mapper to use; never {@code null}
     * @param classes the classes to map
     * @return a comma-separated list of mapped values, or an empty string if
     * the supplied class array is {@code null} or empty
     * @see #nullSafeToString(Class...)
     * @see StringUtils#nullSafeToString(Object)
     */
    public static String nullSafeToString(Function<? super Class<?>, ? extends String> mapper, Class<?>... classes) {
        checkNotNull(mapper, "Mapping function must not be null");

        if (classes == null || classes.length == 0) {
            return "";
        }
        return stream(classes).map(clazz -> clazz == null ? "null" : mapper.apply(clazz)).collect(joining(", "));
    }
}
