name: CI-Maven

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    if: github.repository == 'flowerfine/milky-all'
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        jdk: [ 11 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Java JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk }}
          distribution: temurin
          cache: maven
      - name: Build with Maven
        timeout-minutes: 360
        run: ./mvnw -B -U -T 4C clean package -Dfast
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./**/target/site/jacoco/jacoco.xml
          verbose: true
      
      
