name: CI

on:
  push:
    paths-ignore: ['docs/**', '**/*.md']
    tags-ignore: ['*']
    branches: ['*']
  pull_request:
    paths-ignore: [ 'docs/**', '**/*.md']
  schedule:
    - cron: '0 20 * * *' # automatic test while every day on 04:00 am at UTC+10
  workflow_dispatch:

jobs:

  build_maven:
    uses: ./.github/workflows/ci-maven.yml