name: Sonatype Nexus Deployment

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: maven
          server-id: sonatype-nexus
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET }}
          gpg-passphrase: GPG_PASSWORD
      - name: Publish to Sonatype Nexus
        run: mvn clean deploy -Poss-release -B -DskipTests -Dgpg.passphrase=${{ secrets.GPG_PASSWORD }}
        env:
          OSSRH_USERNAME: ${{ secrets.SONATYPE_USER }}
          OSSRH_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}